[package]
version = "0.1.0"
name = "anime-taste-proof"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sp1-zkvm = "1.1.0"
alloy-sol-types = { workspace = true }
anime-taste-proof-lib = { path = "../lib" }
